export type Club = {
  id: number
  name: string
  state: string
  city: string
  /** [longitude, latitude] */
  coordinates: [number, number]
  /** Pixel offset after projection — avoids overlapping markers */
  markerOffset?: [number, number]
  logo: string
  website?: string
  /** @deprecated use website — kept for ClubLogo / marquee compatibility */
  href?: string | null
  /** @deprecated use logo — kept for ClubLogo / marquee compatibility */
  img?: string | null
}

const WP = 'https://beatscode.com/wp-content/uploads'

/**
 * Lista alinhada à planilha oficial de clientes BeatsCode.
 * Coordenadas em longitude/latitude; markerOffset em px no SVG do mapa.
 */
export const clubs: Club[] = [
  {
    id: 1,
    name: 'América MG',
    state: 'MG',
    city: 'Belo Horizonte',
    coordinates: [-43.9388, -19.9167],
    markerOffset: [-18, 14],
    logo: `${WP}/2023/07/padrao_clubes_0028_America.png`,
    website: 'https://www.americafc.com.br',
  },
  {
    id: 2,
    name: 'Apafut',
    state: 'SP',
    city: 'São Paulo',
    coordinates: [-46.6333, -23.5505],
    markerOffset: [28, 22],
    logo: `${WP}/2023/07/padrao_clubes_0027_apafut.png`,
    website: 'https://www.apafut.com.br',
  },
  {
    id: 3,
    name: 'Aparecidense',
    state: 'GO',
    city: 'Aparecida de Goiânia',
    coordinates: [-49.2447, -16.8198],
    logo: `${WP}/2025/02/05.png`,
    website: 'https://aparecidense.com.br',
  },
  {
    id: 4,
    name: 'Athletic Club',
    state: 'MG',
    city: 'São João del Rei',
    coordinates: [-44.2619, -21.1356],
    logo: `${WP}/2023/07/padrao_clubes_0026_Athletic_Club.png`,
    website: 'https://athleticclub.com.br',
  },
  {
    id: 5,
    name: 'Atlântico Futsal',
    state: 'RS',
    city: 'Erechim',
    coordinates: [-52.2755, -27.6366],
    markerOffset: [16, -10],
    logo: '/clubs/atlantico-futsal.png',
    website: 'https://www.atlanticofutsal.com.br',
  },
  {
    id: 6,
    name: 'Atlético Mineiro',
    state: 'MG',
    city: 'Belo Horizonte',
    coordinates: [-43.9388, -19.9167],
    markerOffset: [0, -16],
    logo: `${WP}/2023/07/padrao_clubes_0025_Atletico-Mineiro.png`,
    website: 'https://www.atletico.com.br',
  },
  {
    id: 7,
    name: 'Avaí',
    state: 'SC',
    city: 'Florianópolis',
    coordinates: [-48.5482, -27.5949],
    markerOffset: [-14, -12],
    logo: `${WP}/2023/07/padrao_clubes_0024_avai-fc-logo-escudo.png`,
    website: 'https://avai.com.br',
  },
  {
    id: 8,
    name: 'Azuriz',
    state: 'PR',
    city: 'Pato Branco',
    coordinates: [-52.6706, -26.2292],
    logo: `${WP}/2023/07/padrao_clubes_0023_Azuriz.png`,
    website: 'https://azuriz.com.br',
  },
  {
    id: 9,
    name: 'Bahia',
    state: 'BA',
    city: 'Salvador',
    coordinates: [-38.5016, -12.9777],
    logo: `${WP}/2023/07/padrao_clubes_0018_e-c-bahia.png`,
    website: 'https://www.esporteclubebahia.com.br',
  },
  {
    id: 10,
    name: 'Boston City FC Brasil',
    state: 'SP',
    city: 'Louveira',
    coordinates: [-46.9506, -23.0864],
    markerOffset: [22, -8],
    logo: `${WP}/2023/07/padrao_clubes_0022_boston-city-fc.png`,
    website: 'https://bostoncityfc.com.br',
  },
  {
    id: 11,
    name: 'Ceará SC',
    state: 'CE',
    city: 'Fortaleza',
    coordinates: [-38.5267, -3.7319],
    logo: `${WP}/2025/02/logo_ceara-1.png`,
    website: 'https://cearasc.com',
  },
  {
    id: 12,
    name: 'Chapecoense',
    state: 'SC',
    city: 'Chapecó',
    coordinates: [-52.6152, -27.1009],
    logo: `${WP}/2023/07/padrao_clubes_0017_Chapecoense.png`,
    website: 'https://chapecoense.com',
  },
  {
    id: 13,
    name: 'Coritiba',
    state: 'PR',
    city: 'Curitiba',
    coordinates: [-49.2731, -25.4284],
    logo: `${WP}/2023/07/logo-coritiba-4096.png`,
    website: 'https://www.coritiba.com.br',
  },
  {
    id: 14,
    name: 'Cruzeiro',
    state: 'MG',
    city: 'Belo Horizonte',
    coordinates: [-43.9388, -19.9167],
    markerOffset: [18, 10],
    logo: `${WP}/2023/07/padrao_clubes_0010_-cruzeiro.png`,
    website: 'https://cruzeiro.com.br',
  },
  {
    id: 15,
    name: 'Cuiabá EC',
    state: 'MT',
    city: 'Cuiabá',
    coordinates: [-56.0979, -15.601],
    logo: `${WP}/2023/07/padrao_clubes_0019_CuiabaEC.png`,
    website: 'https://cuiabaesporteclube.com.br',
  },
  {
    id: 16,
    name: 'EC Noroeste',
    state: 'SP',
    city: 'Bauru',
    coordinates: [-49.0606, -22.3147],
    logo: '/clubs/noroeste.png',
    website: 'https://www.noroeste.com.br',
  },
  {
    id: 17,
    name: 'Ferroviária',
    state: 'SP',
    city: 'Araraquara',
    coordinates: [-48.1756, -21.7845],
    logo: '/clubs/ferroviaria.png',
    website: 'https://ferroviariasaf.com',
  },
  {
    id: 18,
    name: 'Figueirense',
    state: 'SC',
    city: 'Florianópolis',
    coordinates: [-48.5482, -27.5949],
    markerOffset: [14, 10],
    logo: '/clubs/figueirense.png',
    website: 'https://figueirense.com.br',
  },
  {
    id: 19,
    name: 'Flamengo',
    state: 'RJ',
    city: 'Rio de Janeiro',
    coordinates: [-43.1729, -22.9068],
    markerOffset: [-16, -10],
    logo: `${WP}/2023/07/padrao_clubes_0014_flamengo.png`,
    website: 'https://www.flamengo.com.br',
  },
  {
    id: 20,
    name: 'Foothub',
    state: 'SP',
    city: 'São Paulo',
    coordinates: [-46.6333, -23.5505],
    markerOffset: [-30, 8],
    logo: '/clubs/foothub.png',
    website: 'https://foothub.com.br',
  },
  {
    id: 21,
    name: 'Guarani FC',
    state: 'SP',
    city: 'Campinas',
    coordinates: [-47.0608, -22.9056],
    markerOffset: [-14, -12],
    logo: '/clubs/guarani.png',
    website: 'https://guaranifc.com.br',
  },
  {
    id: 22,
    name: 'i9 Futebol Clube Academy',
    state: 'SP',
    city: 'São Paulo',
    coordinates: [-46.6333, -23.5505],
    markerOffset: [8, 32],
    logo: '/clubs/i9.png',
    website: 'https://www.instagram.com/i9futebolclube/',
  },
  {
    id: 23,
    name: 'IAPE Futebol Clube',
    state: 'MA',
    city: 'São Luís',
    coordinates: [-44.3028, -2.5307],
    logo: '/clubs/iape.png',
    website: 'https://www.iapefc.com.br',
  },
  {
    id: 24,
    name: 'Ibrachina FC',
    state: 'SP',
    city: 'São Paulo',
    coordinates: [-46.6333, -23.5505],
    markerOffset: [-18, -22],
    logo: `${WP}/2023/07/padrao_clubes_0012_IBRACHINA.png`,
    website: 'https://ibrachinafc.com.br',
  },
  {
    id: 25,
    name: 'Sport Club Internacional',
    state: 'RS',
    city: 'Porto Alegre',
    coordinates: [-51.2177, -30.0346],
    logo: `${WP}/2023/07/padrao_clubes_0011_Internacional.png`,
    website: 'https://internacional.com.br',
  },
  {
    id: 26,
    name: 'EC Juventude',
    state: 'RS',
    city: 'Caxias do Sul',
    coordinates: [-51.1794, -29.1681],
    markerOffset: [14, -8],
    logo: `${WP}/2025/02/02.png`,
    website: 'https://juventude.com.br',
  },
  {
    id: 27,
    name: 'Manauara EC',
    state: 'AM',
    city: 'Manaus',
    coordinates: [-60.0217, -3.119],
    logo: '/clubs/manauara.png',
    website: 'https://manauaraec.com.br',
  },
  {
    id: 28,
    name: 'Marcílio Dias',
    state: 'SC',
    city: 'Itajaí',
    coordinates: [-48.6615, -26.9078],
    logo: `${WP}/2023/07/padrao_clubes_0009_Nautico-MarcIlio-Dias.png`,
    website: 'https://marciliodias.com.br',
  },
  {
    id: 29,
    name: 'Clube Náutico Capibaribe',
    state: 'PE',
    city: 'Recife',
    coordinates: [-34.8811, -8.0476],
    markerOffset: [-16, -12],
    logo: `${WP}/2025/02/03.png`,
    website: 'https://nautico-pe.com.br',
  },
  {
    id: 30,
    name: 'Novorizontino',
    state: 'SP',
    city: 'Novo Horizonte',
    coordinates: [-49.223, -21.0039],
    logo: `${WP}/2023/07/padrao_clubes_0007_Novorizontino.png`,
    website: 'https://gremionovorizontino.com.br',
  },
  {
    id: 31,
    name: 'Palmeiras',
    state: 'SP',
    city: 'São Paulo',
    coordinates: [-46.6792, -23.5275],
    markerOffset: [0, -28],
    logo: `${WP}/2023/07/padrao_clubes_0006_Palmeiras.png`,
    website: 'https://www.palmeiras.com.br',
  },
  {
    id: 32,
    name: 'Paysandu',
    state: 'PA',
    city: 'Belém',
    coordinates: [-48.5044, -1.4558],
    logo: `${WP}/2025/02/logo_paysandu-1.png`,
    website: 'https://paysandu.com.br',
  },
  {
    id: 33,
    name: 'Pinda FC',
    state: 'SP',
    city: 'Pindamonhangaba',
    coordinates: [-45.4612, -22.9056],
    logo: `${WP}/2025/02/04.png`,
    website: 'https://pindafc.com.br',
  },
  {
    id: 34,
    name: 'Primavera AC',
    state: 'SP',
    city: 'Indaiatuba',
    coordinates: [-47.2119, -23.0884],
    markerOffset: [16, 14],
    logo: '/clubs/primavera.png',
    website: 'https://www.instagram.com/ecprimavera/',
  },
  {
    id: 35,
    name: 'Real Soccer',
    state: 'SP',
    city: 'São Paulo',
    coordinates: [-46.6333, -23.5505],
    markerOffset: [32, -18],
    logo: '/clubs/real-soccer.png',
    website: 'https://www.instagram.com/realsoccerbrasil/',
  },
  {
    id: 36,
    name: 'Santa Cruz FC',
    state: 'PE',
    city: 'Recife',
    coordinates: [-34.8811, -8.0476],
    markerOffset: [16, 12],
    logo: '/clubs/santa-cruz.png',
    website: 'https://santacruzpe.com.br',
  },
  {
    id: 37,
    name: 'Santos FC',
    state: 'SP',
    city: 'Santos',
    coordinates: [-46.3322, -23.9515],
    logo: `${WP}/2023/07/padrao_clubes_0004_Santos.png`,
    website: 'https://www.santosfc.com.br',
  },
  {
    id: 38,
    name: 'São Paulo FC',
    state: 'SP',
    city: 'São Paulo',
    coordinates: [-46.6995, -23.5855],
    markerOffset: [16, 6],
    logo: `${WP}/2025/02/01.png`,
    website: 'https://www.saopaulofc.net',
  },
  {
    id: 39,
    name: 'Sfera FC',
    state: 'SP',
    city: 'Várzea Paulista',
    coordinates: [-46.8281, -23.2136],
    markerOffset: [-20, 16],
    logo: '/clubs/sfera.png',
    website: 'https://sferafc.com.br/',
  },
  {
    id: 40,
    name: 'Sport Club do Recife',
    state: 'PE',
    city: 'Recife',
    coordinates: [-34.8811, -8.0476],
    markerOffset: [0, -18],
    logo: `${WP}/2023/07/padrao_clubes_0002_Sportrecife.png`,
    website: 'https://www.sportrecife.com.br',
  },
  {
    id: 41,
    name: 'Uberlândia EC',
    state: 'MG',
    city: 'Uberlândia',
    coordinates: [-48.2772, -18.9186],
    logo: '/clubs/uberlandia.png',
    website: 'https://uberlandiaesporte.com.br',
  },
  {
    id: 42,
    name: 'CR Vasco da Gama',
    state: 'RJ',
    city: 'Rio de Janeiro',
    coordinates: [-43.1729, -22.9068],
    markerOffset: [16, 12],
    logo: `${WP}/2023/07/padrao_clubes_0001_vasco.png`,
    website: 'https://www.vasco.com.br',
  },
  {
    id: 43,
    name: 'Ypiranga FC',
    state: 'RS',
    city: 'Erechim',
    coordinates: [-52.2755, -27.6366],
    markerOffset: [-14, 12],
    logo: `${WP}/2025/02/Ypiranga_Futebol_Clube.png`,
    website: 'https://www.yfc.com.br',
  },
].map(
  (club): Club => ({
    ...club,
    coordinates: club.coordinates as [number, number],
    markerOffset: club.markerOffset as [number, number] | undefined,
    href: club.website ?? null,
    img: club.logo,
  })
)

export const clubsCount = clubs.length

/** Centróides aproximados por UF — usados no agrupamento mobile */
export const STATE_CENTROIDS: Record<string, [number, number]> = {
  AC: [-70.55, -9.02],
  AL: [-36.65, -9.57],
  AM: [-64.0, -4.0],
  AP: [-51.77, 1.41],
  BA: [-41.7, -12.5],
  CE: [-39.3, -5.2],
  DF: [-47.88, -15.78],
  ES: [-40.3, -19.6],
  GO: [-49.6, -15.9],
  MA: [-45.0, -5.0],
  MG: [-44.4, -18.5],
  MS: [-54.5, -20.5],
  MT: [-55.9, -12.6],
  PA: [-52.0, -3.5],
  PB: [-36.5, -7.1],
  PE: [-37.0, -8.3],
  PI: [-42.8, -7.0],
  PR: [-51.2, -24.5],
  RJ: [-42.7, -22.2],
  RN: [-36.5, -5.8],
  RO: [-63.0, -11.0],
  RR: [-61.3, 1.9],
  RS: [-53.0, -30.0],
  SC: [-50.5, -27.2],
  SE: [-37.4, -10.6],
  SP: [-48.5, -22.3],
  TO: [-48.3, -10.2],
}

export const STATE_NAMES: Record<string, string> = {
  AC: 'Acre',
  AL: 'Alagoas',
  AM: 'Amazonas',
  AP: 'Amapá',
  BA: 'Bahia',
  CE: 'Ceará',
  DF: 'Distrito Federal',
  ES: 'Espírito Santo',
  GO: 'Goiás',
  MA: 'Maranhão',
  MG: 'Minas Gerais',
  MS: 'Mato Grosso do Sul',
  MT: 'Mato Grosso',
  PA: 'Pará',
  PB: 'Paraíba',
  PE: 'Pernambuco',
  PI: 'Piauí',
  PR: 'Paraná',
  RJ: 'Rio de Janeiro',
  RN: 'Rio Grande do Norte',
  RO: 'Rondônia',
  RR: 'Roraima',
  RS: 'Rio Grande do Sul',
  SC: 'Santa Catarina',
  SE: 'Sergipe',
  SP: 'São Paulo',
  TO: 'Tocantins',
}

export type BrazilRegion =
  | 'norte'
  | 'nordeste'
  | 'centro-oeste'
  | 'sudeste'
  | 'sul'

export const REGION_NAMES: Record<BrazilRegion, string> = {
  norte: 'Norte',
  nordeste: 'Nordeste',
  'centro-oeste': 'Centro-Oeste',
  sudeste: 'Sudeste',
  sul: 'Sul',
}

/** Soft fills per Brazilian region (map + legend) */
export const REGION_COLORS: Record<
  BrazilRegion,
  { fill: string; hover: string; accent: string }
> = {
  norte: { fill: '#C8E8DE', hover: '#A9D9C9', accent: '#1A8F6E' },
  nordeste: { fill: '#F3E0B8', hover: '#E8CE92', accent: '#C4841D' },
  'centro-oeste': { fill: '#E4ECC0', hover: '#D2DE9A', accent: '#7A9420' },
  sudeste: { fill: '#D7EFD9', hover: '#BBE0BF', accent: '#00A651' },
  sul: { fill: '#D3E4F5', hover: '#B5D0EB', accent: '#2F6FAF' },
}

export const STATE_REGION: Record<string, BrazilRegion> = {
  AC: 'norte',
  AP: 'norte',
  AM: 'norte',
  PA: 'norte',
  RO: 'norte',
  RR: 'norte',
  TO: 'norte',
  AL: 'nordeste',
  BA: 'nordeste',
  CE: 'nordeste',
  MA: 'nordeste',
  PB: 'nordeste',
  PE: 'nordeste',
  PI: 'nordeste',
  RN: 'nordeste',
  SE: 'nordeste',
  DF: 'centro-oeste',
  GO: 'centro-oeste',
  MT: 'centro-oeste',
  MS: 'centro-oeste',
  ES: 'sudeste',
  MG: 'sudeste',
  RJ: 'sudeste',
  SP: 'sudeste',
  PR: 'sul',
  RS: 'sul',
  SC: 'sul',
}

export const REGION_ORDER: BrazilRegion[] = [
  'norte',
  'nordeste',
  'centro-oeste',
  'sudeste',
  'sul',
]

export function getStateRegion(uf: string): BrazilRegion | null {
  return STATE_REGION[uf] ?? null
}

export function openClubWebsite(club: Club) {
  if (!club.website) return
  window.open(club.website, '_blank', 'noopener,noreferrer')
}

export const LOGO_URL = `${WP}/2022/02/beatscode-logo-3-300x102.png`
/** Visual do hero — captura da plataforma (local, sem a foto do técnico) */
export const PLATFORM_IMG = '/hero/solucoes.png'
export const HERO_PLATFORM_IMG = '/hero/platform.webp'
